# Generated by Django 4.1.7 on 2023-12-04 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=3000, unique=True
            ),
            preserve_default=False,
        ),
    ]
