#!/bin/bash

set -o errexit
set -o nounset

# TODO: Change -A with your django project name (Change "Core")
exec watchfiles celery.__main__.main \
    --args \
    "-A core.celery -b \"${CELERY_BROKER_URL}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""